(setq ll (make-array 7 :initial-element 0))
(setq li (make-array 7 :initial-element nil))
(defun permulation (n)
    (if (= 7 n)
        (print ll)
        (progn
        (labels ((for (m)
            (if (= 7 m)
            ()
            (progn
            (if (aref li m)
                (for (1+ m))
                (progn
                (setf (aref ll n) (1+ m))
                (setf (aref li m ) t )
                (permulation (1+ n))
                (setf (aref li m ) nil)
                (for (1+ m))))))))
        (for 0)))))
(defun lengt (lli)
    (if (null lli)
        0
        (1+ (lengt (cdr lli)))))
(defun leng (lli)
    (labels ((len (ls)
        (if (null ls)
        0
        (1+ (len (cdr ls))))))
    (len lli)))
(defun len (lli &optional (count 0))
    (cond 
    ((null lli) count)
    (t (len (cdr lli) (1+ count)))))    
(setq lis '(1 2 3 4 5 6 7 8 9))
(defun sq (x)
    (* x x))
(defun change (lis &optional(f (lambda (x) (x))))
    (cond
    ((null lis) f )
    ( t (progn
            (rplaca lis (funcall f (car lis)))
            (change (cdr lis) f)
            f))))
;(change lis (change lis (lambda (x) (* x x))))
(setq lis '(1 2 3 4 5 6 7 8 9))
(defun make-counter (n)
  (let ((count 0))
    (lambda ()
      (incf count)
      count)))
(setq counter1 (make-counter 1))
(setq counter2 (make-counter 2))
(setq hh
      (lambda ()
        (setq i 0)
        (loop while (< i 6)
              do (print (funcall counter1))
                 (incf i))))

(funcall hh)
